### ISSUE TITLE
Unescape all exception messages

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-price-feeds-poller#57]
As to avoid parsing error conditions in Grafana logs.

**Comment by guidiaz** [comment]
Detected two unrelated issues:
- latest version of witnet-toolkit binary is not compatible w/ container's base distro
- bridge jumps over new queries if an rpc provider error arises while getting the query's bytecode, whereas it should jump over only if an evm revert is produced, and retry as many times as required otherwise

**Comment by aesedepece** [comment]
>     * latest version of witnet-toolkit binary is not compatible w/ container's base distro
Fixed in #58 

>     * bridge jumps over new queries if an rpc provider error arises while getting the query's bytecode, whereas it should jump over only if an evm revert is produced, and retry as many times as required otherwise
That'll be https://github.com/witnet/witnet-rust/issues/2388. Working on it!

**Comment by guidiaz** [comment]
New base docker image included within fix #58, works fine and smoothly.

**Comment by guidiaz** [comment]
Related PRs:
- https://github.com/witnet/witnet-price-feeds-poller/pull/59
-

**Comment by guidiaz** [comment]
Updating all testnets to use:
- Bridge v1.6.6
- Poller v2.0.5
