### ISSUE TITLE
Fix: Avoid false positives upon pfs reloading

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-price-feeds-poller#73]
Test and then upgrade Poller instance on all testnest and mainnets.

**Comment by aesedepece** [comment]
@guidiaz mentioned that there's a related PR.

**Comment by aesedepece** [comment]
@guidiaz mentioned that there's a related PR.

**Comment by aesedepece** [comment]
@guidiaz mentioned that there's a related PR.

**Comment by guidiaz** [comment]
Related PRs:
- https://github.com/witnet/witnet-price-feeds-poller/pull/72
- https://github.com/otherplane/bridge-iac/pull/211
